INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (1, 'Prima visita (nuovo paziente)', 30, NULL, 55, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (2, 'Visita di controllo', 20, NULL, 40, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (3, 'Visita clinica generale', 30, NULL, 50, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (4, 'Visita geriatrica (animali > 7 anni)', 45, NULL, 65, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (5, 'Vaccinazione singola dose', 15, NULL, 35, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (6, 'Vaccinazione polivalente cane (DHPPI+L)', 20, NULL, 55, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (7, 'Vaccinazione antirabbica', 15, NULL, 40, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (8, 'Richiamo annuale vaccinazioni', 20, NULL, 50, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (9, 'Sverminazione', 10, NULL, 20, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (10, 'Antiparassitario topico (applicazione)', 10, NULL, 20, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (11, 'Microchippatura', 15, NULL, 30, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (12, 'Prelievo ematico', 15, NULL, 25, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (13, 'Ecografia addominale', 30, NULL, 90, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (14, 'Ecografia cardiaca', 45, NULL, 110, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (15, 'Radiografia (fino a 2 proiezioni)', 20, NULL, 80, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (16, 'Misurazione pressione arteriosa', 15, NULL, 25, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (17, 'Elettrocardiogramma (ECG)', 20, NULL, 60, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (18, 'Esame citologico cutaneo', 20, NULL, 45, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (19, 'Otoscopia ed esame auricolare', 20, NULL, 35, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (20, 'Visita dermatologica', 30, NULL, 65, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (21, 'Visita oculistica', 30, NULL, 70, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (22, 'Visita ortopedica', 45, NULL, 75, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (23, 'Consulenza comportamentale', 45, NULL, 70, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (24, 'Visita nutrizionale e dietetica', 30, NULL, 45, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (25, 'Visita odontoiatrica', 20, NULL, 40, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (26, 'Detartrasi (pulizia tartaro in anestesia)', 60, NULL, 130, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (27, 'Sterilizzazione gatta', 60, NULL, 180, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (28, 'Castrazione gatto maschio', 45, NULL, 120, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (29, 'Sterilizzazione cagna (≤ 10 kg)', 75, NULL, 250, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (30, 'Sterilizzazione cagna (10–25 kg)', 90, NULL, 320, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (31, 'Sterilizzazione cagna (> 25 kg)', 105, NULL, 400, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (32, 'Castrazione cane maschio', 60, NULL, 200, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (33, 'Medicazione ferita semplice', 20, NULL, 35, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (34, 'Medicazione ferita complessa / bendaggio', 30, NULL, 55, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (35, 'Rimozione punti di sutura', 15, NULL, 25, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (36, 'Iniezione intramuscolare / sottocutanea', 10, NULL, 20, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (37, 'Infusione endovenosa', 30, NULL, 45, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (38, 'Lavaggio auricolare', 15, NULL, 30, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (39, 'Taglio unghie', 10, NULL, 15, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (40, 'Visita d''urgenza (in orario)', 30, NULL, 85, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES (41, 'Visita fuori orario / reperibilità', 30, NULL, 110, 1, NULL, 0);
INSERT INTO TIPI_VISITE ("ID", "Nome", "Durata", "ID_Categoria", "Prezzo", "attivo", "ID_Dottore", "isDeleted") VALUES ('Totale: 41 tipi di visita', NULL, 25569.041666666668, NULL, 0.0, 1, NULL, 0);

