-- JDBC SQL dump generated from the live PostgreSQL database
-- Generated at: 2026-07-13T20:32:16.2838511

BEGIN;

CREATE TYPE public."stato_visita" AS ENUM ('PRENOTATA', 'COMPLETATA');

CREATE TABLE public."animali" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nome" VARCHAR(30) NOT NULL,
    "specie" VARCHAR(15),
    "razza" VARCHAR(20),
    "sesso" VARCHAR(10),
    "data_nascita" DATE NOT NULL,
    "peso" DOUBLE PRECISION,
    "microchip" VARCHAR(15),
    "note" TEXT,
    "id_utente" INTEGER NOT NULL,
    "is_deleted" BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE public."aziende" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "ragione_sociale" VARCHAR(100) NOT NULL,
    "partita_iva" VARCHAR(11) NOT NULL,
    "forma_giuridica" VARCHAR(100) NOT NULL,
    "is_deleted" BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE public."categorie_visite" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nome" VARCHAR(100) NOT NULL,
    "is_deleted" BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE public."eventi_app" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_utente" INTEGER NOT NULL,
    "id_ruolo" INTEGER NOT NULL,
    "tipo_evento" VARCHAR(20) NOT NULL,
    "id_oggetto" INTEGER,
    "oggetto_azione" VARCHAR(30),
    "time_stamp" TIMESTAMP WITHOUT TIME ZONE,
    "metadata" JSONB,
    "is_deleted" BOOLEAN
);

CREATE TABLE public."file_reference" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "original_file_name" VARCHAR(255) NOT NULL,
    "stored_file_name" VARCHAR(255) NOT NULL,
    "mime_type" VARCHAR(255) NOT NULL,
    "ssize" BIGINT NOT NULL,
    "storage_path" VARCHAR(255) NOT NULL,
    "owner" INTEGER NOT NULL,
    "upload_date" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "is_deleted" BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE public."orario_settimanale" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "giorno_settimana" INTEGER NOT NULL,
    "mattina_inizio" INTEGER NOT NULL,
    "mattina_fine" INTEGER NOT NULL,
    "pomeriggio_inizio" INTEGER NOT NULL,
    "pomeriggio_fine" INTEGER NOT NULL,
    "id_utente" INTEGER NOT NULL
);

CREATE TABLE public."pagamenti" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "data" DATE NOT NULL,
    "tipo_pagamento" VARCHAR(30),
    "importo_totale" NUMERIC(8, 2) NOT NULL,
    "id_utente" INTEGER,
    "riferimento_file" INTEGER,
    "is_deleted" BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE public."razze" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nome" VARCHAR(255) NOT NULL,
    "id_specie" INTEGER NOT NULL,
    "is_deleted" BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE public."ruoli" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "ruolo" VARCHAR(15) NOT NULL
);

CREATE TABLE public."specie" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nome" VARCHAR(255) NOT NULL,
    "is_deleted" BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE public."tipi_vaccino" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "tipologia" VARCHAR(255) NOT NULL,
    "durata" INTEGER NOT NULL,
    "note" VARCHAR(255),
    "is_deleted" BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE public."tipi_visite" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nome" VARCHAR(80) NOT NULL,
    "durata" INTEGER NOT NULL,
    "id_categoria" INTEGER,
    "prezzo" NUMERIC(8, 2) NOT NULL,
    "id_dottore" INTEGER NOT NULL,
    "attivo" BOOLEAN NOT NULL DEFAULT true,
    "is_deleted" BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE public."utenti" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nome" VARCHAR(30) NOT NULL,
    "cognome" VARCHAR(30) NOT NULL,
    "email" VARCHAR(100) NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    "telefono" VARCHAR(20) NOT NULL,
    "indirizzo" VARCHAR(30),
    "citta" VARCHAR(20),
    "data_registrazione" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "id_azienda" INTEGER,
    "codice_fiscale" VARCHAR(16) NOT NULL,
    "id_ruolo" INTEGER NOT NULL,
    "is_deleted" BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE public."vaccinazioni" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "id_tipo" INTEGER NOT NULL,
    "data_vaccinazione" TIMESTAMP WITHOUT TIME ZONE,
    "lotto" VARCHAR(255),
    "id_animale" INTEGER NOT NULL,
    "is_deleted" BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE public."visita" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "data_visita" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "id_tipo_visita" INTEGER NOT NULL,
    "id_animale" INTEGER NOT NULL,
    "id_veterinario" INTEGER NOT NULL,
    "id_pagamento" INTEGER,
    "note" VARCHAR(255),
    "is_deleted" BOOLEAN NOT NULL DEFAULT false,
    "nota_privata" TEXT,
    "stato" public."stato_visita" NOT NULL
);

COPY public."animali" ("id", "nome", "specie", "razza", "sesso", "data_nascita", "peso", "microchip", "note", "id_utente", "is_deleted") FROM stdin;
1	Briciola	Cane	Labrador	F	2017-05-12	28.5	380260040123456	\N	1	f
2	Rex	Cane	Pastore Tedesco	M	2018-09-03	34	380260040234567	Allergia al pollame	2	f
3	Luna	Gatto	Europeo Comune	F	2020-02-17	4.2	380260040345678	\N	2	f
4	Pallina	Cane	Bassotto	F	2016-11-28	9.1	380260040456789	Problemi alla schiena	3	f
5	Micio	Gatto	Persiano	M	2019-04-06	5.8	380260040567890	\N	4	f
6	Fido	Cane	Golden Retriever	M	2018-08-14	31.2	380260040678901	\N	5	f
7	Neve	Gatto	Siamese	F	2021-01-22	3.9	380260040789012	\N	6	f
8	Birillo	Cane	Beagle	M	2017-06-09	12.4	380260040890123	Tendenza all'obesità	7	f
9	Cioccolata	Cane	Labrador	F	2019-03-30	26	380260040901234	\N	8	f
10	Tigre	Gatto	Maine Coon	M	2018-10-11	7.3	380260041012345	\N	9	f
11	Oscar	Cane	Boxer	M	2020-07-05	29.5	380260041123456	\N	10	f
12	Puffo	Coniglio	Nano Olandese	M	2021-12-18	1.4	\N	\N	11	f
13	Stella	Gatto	Europeo Comune	F	2019-05-24	3.6	380260041234567	FIV positivo	12	f
14	Zeus	Cane	Rottweiler	M	2017-02-02	44	380260041345678	\N	13	f
15	Mia	Gatto	Ragdoll	F	2020-09-16	5.1	380260041456789	\N	14	f
16	Artù	Cane	Border Collie	M	2018-11-07	18.7	380260041567890	\N	15	f
17	Mochi	Gatto	Birmano	M	2021-06-29	4.4	380260041678901	\N	1	f
18	Lilly	Cane	Barboncino	F	2020-03-13	5.2	380260041789012	\N	5	f
19	Charlie	Cane	Cocker Spaniel	M	2019-08-25	11.8	380260041890123	Otite cronica	8	f
20	Fiocco	Coniglio	Ariete	F	2022-01-04	2.1	\N	\N	11	f
\.

COPY public."aziende" ("id", "ragione_sociale", "partita_iva", "forma_giuridica", "is_deleted") FROM stdin;
\.

COPY public."categorie_visite" ("id", "nome", "is_deleted") FROM stdin;
1	Routine	f
2	Prevenzione	f
3	Diagnostica	f
4	Specialistica	f
5	Odontoiatria	f
6	Chirurgia	f
7	Piccoli interventi	f
8	Urgenze	f
\.

COPY public."eventi_app" ("id", "id_utente", "id_ruolo", "tipo_evento", "id_oggetto", "oggetto_azione", "time_stamp", "metadata", "is_deleted") FROM stdin;
\.

COPY public."file_reference" ("id", "original_file_name", "stored_file_name", "mime_type", "ssize", "storage_path", "owner", "upload_date", "is_deleted") FROM stdin;
\.

COPY public."orario_settimanale" ("id", "giorno_settimana", "mattina_inizio", "mattina_fine", "pomeriggio_inizio", "pomeriggio_fine", "id_utente") FROM stdin;
\.

COPY public."pagamenti" ("id", "data", "tipo_pagamento", "importo_totale", "id_utente", "riferimento_file", "is_deleted") FROM stdin;
\.

COPY public."razze" ("id", "nome", "id_specie", "is_deleted") FROM stdin;
1	Labrador	1	f
2	Pastore Tedesco	1	f
3	Europeo Comune	2	f
4	Bassotto	1	f
5	Persiano	2	f
6	Golden Retriever	1	f
7	Siamese	2	f
8	Beagle	1	f
9	Maine Coon	2	f
10	Boxer	1	f
11	Nano Olandese	3	f
12	Rottweiler	1	f
13	Ragdoll	2	f
14	Border Collie	1	f
15	Birmano	2	f
16	Barboncino	1	f
17	Cocker Spaniel	1	f
18	Ariete	3	f
19	Bouledogue Francese	1	f
20	Bulldog	1	f
21	Bracco Tedesco	1	f
22	Yorkshire Terrier	1	f
23	Pastore Australiano	1	f
24	Cavalier King Charles Spaniel	1	f
25	Cane Corso	1	f
26	Welsh Corgi Pembroke	1	f
27	Dobermann	1	f
28	Schnauzer Nano	1	f
29	Bovaro del Bernese	1	f
30	Shih Tzu	1	f
31	Alano	1	f
32	Volpino di Pomerania	1	f
33	Boston Terrier	1	f
34	Havanese	1	f
35	Siberian Husky	1	f
36	Chihuahua	1	f
37	Springer Spaniel Inglese	1	f
38	Shetland Sheepdog	1	f
39	British Shorthair	2	f
40	Bengal	2	f
41	Sphynx	2	f
42	Abissino	2	f
43	Siberiano	2	f
44	Exotic Shorthair	2	f
45	Holland Lop	3	f
46	Mini Lop	3	f
47	Mini Rex	3	f
48	Lionhead	3	f
\.

COPY public."ruoli" ("id", "ruolo") FROM stdin;
1	CLIENTE
2	VETERINARIO
3	RECEPTIONIST
4	ADMIN
\.

COPY public."specie" ("id", "nome", "is_deleted") FROM stdin;
1	Cane	f
2	Gatto	f
3	Coniglio	f
\.

COPY public."tipi_vaccino" ("id", "tipologia", "durata", "note", "is_deleted") FROM stdin;
1	Polivalente cane (DHPPI)	366	Duration inferred from Data Scadenza in Dati_file_unico.xlsx.	f
2	Antirabbico	1096	Duration inferred from Data Scadenza in Dati_file_unico.xlsx.	f
3	Trivalente felina (HCP)	366	Duration inferred from Data Scadenza in Dati_file_unico.xlsx.	f
4	Leucemia felina (FeLV)	366	Duration inferred from Data Scadenza in Dati_file_unico.xlsx.	f
5	Leishmaniosi	366	Duration inferred from Data Scadenza in Dati_file_unico.xlsx.	f
\.

COPY public."tipi_visite" ("id", "nome", "durata", "id_categoria", "prezzo", "id_dottore", "attivo", "is_deleted") FROM stdin;
1	Prima visita (nuovo paziente)	30	1	55.00	16	t	f
2	Visita di controllo	20	1	40.00	17	t	f
3	Visita clinica generale	30	1	50.00	18	t	f
4	Visita geriatrica (animali > 7 anni)	45	1	65.00	16	t	f
5	Vaccinazione singola dose	15	2	35.00	17	t	f
6	Vaccinazione polivalente cane (DHPPI+L)	20	2	55.00	18	t	f
7	Vaccinazione antirabbica	15	2	40.00	16	t	f
8	Richiamo annuale vaccinazioni	20	2	50.00	17	t	f
9	Sverminazione	10	2	20.00	18	t	f
10	Antiparassitario topico (applicazione)	10	2	20.00	16	t	f
11	Microchippatura	15	2	30.00	17	t	f
12	Prelievo ematico	15	3	25.00	18	t	f
13	Ecografia addominale	30	3	90.00	16	t	f
14	Ecografia cardiaca	45	3	110.00	17	t	f
15	Radiografia (fino a 2 proiezioni)	20	3	80.00	18	t	f
16	Misurazione pressione arteriosa	15	3	25.00	16	t	f
17	Elettrocardiogramma (ECG)	20	3	60.00	17	t	f
18	Esame citologico cutaneo	20	3	45.00	18	t	f
19	Otoscopia ed esame auricolare	20	3	35.00	16	t	f
20	Visita dermatologica	30	4	65.00	17	t	f
21	Visita oculistica	30	4	70.00	18	t	f
22	Visita ortopedica	45	4	75.00	16	t	f
23	Consulenza comportamentale	45	4	70.00	17	t	f
24	Visita nutrizionale e dietetica	30	4	45.00	18	t	f
25	Visita odontoiatrica	20	5	40.00	16	t	f
26	Detartrasi (pulizia tartaro in anestesia)	60	5	130.00	17	t	f
27	Sterilizzazione gatta	60	6	180.00	18	t	f
28	Castrazione gatto maschio	45	6	120.00	16	t	f
29	Sterilizzazione cagna (≤ 10 kg)	75	6	250.00	17	t	f
30	Sterilizzazione cagna (10–25 kg)	90	6	320.00	18	t	f
31	Sterilizzazione cagna (> 25 kg)	105	6	400.00	16	t	f
32	Castrazione cane maschio	60	6	200.00	17	t	f
33	Medicazione ferita semplice	20	7	35.00	18	t	f
34	Medicazione ferita complessa / bendaggio	30	7	55.00	16	t	f
35	Rimozione punti di sutura	15	7	25.00	17	t	f
36	Iniezione intramuscolare / sottocutanea	10	7	20.00	18	t	f
37	Infusione endovenosa	30	7	45.00	16	t	f
38	Lavaggio auricolare	15	7	30.00	17	t	f
39	Taglio unghie	10	7	15.00	18	t	f
40	Visita d'urgenza (in orario)	30	8	85.00	16	t	f
41	Visita fuori orario / reperibilità	30	8	110.00	17	t	f
\.

COPY public."utenti" ("id", "nome", "cognome", "email", "password", "telefono", "indirizzo", "citta", "data_registrazione", "id_azienda", "codice_fiscale", "id_ruolo", "is_deleted") FROM stdin;
1	Marco	Rossi	marco.rossi@email.it	$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy	335 1234567	Via Roma 12	Bergamo	2019-03-15 09:00:00	\N	SEEDCLIENTE0001	1	f
2	Francesca	Bianchi	f.bianchi@gmail.com	$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy	347 2345678	Via Garibaldi 5	Bergamo Alta	2019-07-22 09:00:00	\N	SEEDCLIENTE0002	1	f
3	Luigi	Colombo	l.colombo@libero.it	$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy	328 3456789	Via Manzoni 33	Sorisole	2019-11-10 09:00:00	\N	SEEDCLIENTE0003	1	f
4	Anna	Ferrari	anna.ferrari@yahoo.it	$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy	339 4567890	Piazza Vecchia 1	Bergamo Alta	2020-02-05 09:00:00	\N	SEEDCLIENTE0004	1	f
5	Giorgio	Ricci	g.ricci@email.it	$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy	366 5678901	Via Tasso 8	Bergamo	2020-04-18 09:00:00	\N	SEEDCLIENTE0005	1	f
6	Maria	Conti	maria.conti@gmail.com	$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy	351 6789012	Via Pignolo 44	Bergamo	2020-06-30 09:00:00	\N	SEEDCLIENTE0006	1	f
7	Paolo	Manzoni	p.manzoni@libero.it	$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy	342 7890123	Via Borgo Palazzo 17	Bergamo	2020-09-12 09:00:00	\N	SEEDCLIENTE0007	1	f
8	Elena	Galli	e.galli@email.it	$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy	333 8901234	Via S. Tomaso 9	Bergamo Alta	2021-01-25 09:00:00	\N	SEEDCLIENTE0008	1	f
9	Roberto	Esposito	r.esposito@gmail.com	$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy	370 9012345	Via Zambonate 22	Bergamo	2021-03-08 09:00:00	\N	SEEDCLIENTE0009	1	f
10	Chiara	Ferretti	c.ferretti@email.it	$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy	348 0123456	Viale Papa Giovanni 15	Bergamo	2021-05-19 09:00:00	\N	SEEDCLIENTE0010	1	f
11	Antonio	Moretti	a.moretti@libero.it	$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy	335 1234568	Via Tiraboschi 6	Bergamo	2021-08-02 09:00:00	\N	SEEDCLIENTE0011	1	f
12	Valentina	Caruso	v.caruso@gmail.com	$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy	347 2345679	Via Quarenghi 11	Bergamo	2021-10-14 09:00:00	\N	SEEDCLIENTE0012	1	f
13	Francesco	Lombardi	f.lombardi@email.it	$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy	328 3456780	Via Moroni 28	Bergamo	2021-12-27 09:00:00	\N	SEEDCLIENTE0013	1	f
14	Giulia	Barbieri	g.barbieri@yahoo.it	$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy	339 4567891	Via Camozzi 3	Bergamo	2022-02-09 09:00:00	\N	SEEDCLIENTE0014	1	f
15	Stefano	Marchetti	s.marchetti@gmail.com	$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy	366 5678902	Via Angelo Mai 19	Bergamo Alta	2022-04-21 09:00:00	\N	SEEDCLIENTE0015	1	f
16	Laura	Verdi	laura.verdi@clinicazampetti.it	$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy	035 1110001	Via Zambonate 1	Bergamo	2024-01-01 09:00:00	\N	VRDLRA85A41A794K	2	f
17	Matteo	Sala	matteo.sala@clinicazampetti.it	$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy	035 1110002	Via Zambonate 1	Bergamo	2024-01-01 09:00:00	\N	SLAMTT82B12A794R	2	f
18	Sara	Neri	sara.neri@clinicazampetti.it	$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy	035 1110003	Via Zambonate 1	Bergamo	2024-01-01 09:00:00	\N	NRESRA90C53A794V	2	f
19	Camillo	Zampetti	camillo.zampetti@clinicazampetti.it	$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy	035 1110004	Via Zambonate 1	Bergamo	2024-01-01 09:00:00	\N	ZMPCLL80A01A794Z	3	f
20	Admin	Zampetti	admin@clinicazampetti.it	$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy	035 1110000	Via Zambonate 1	Bergamo	2024-01-01 09:00:00	\N	ZMPDMN80A01A794Z	4	f
23	Test	User	codex-test-174112@example.com	$2a$10$ULHsaavc22j5psPSlqTfqeNBo4WcX69piHFXENUG1PzYGEAfOOuP.	1234567890	\N	\N	2026-07-13 17:41:12.637909	\N	TSTCDX90A01H1741	1	f
25	Test	User	codex-test-2dcaadfe@example.com	$2a$10$JRMoF7O30pE8q8S03N6r3uQiKc6zn2YInzLbDMH4ma.8tG3z7r..W	1234567890	\N	\N	2026-07-13 17:41:45.580121	\N	CF2DCAADFE7B7241	1	f
26	Test	User	codex-test-d55a7dc4@example.com	$2a$10$gQnXQf14vNTNhZzHXBbYee65x.P9leKKqs1g/0jhH1t4AGU6VKaEC	1234567890	\N	\N	2026-07-13 17:42:34.28006	\N	CFD55A7DC4A05340	1	f
27	Andrea	Chiampo	andrea.chiampo@edu-its.it	$2a$10$bmad9KhIxZFsJmhgOYIXseA1/FKGJVNb/Y8bUXVFuAiPi.6QtH1u.	1234567890	\N	\N	2026-07-13 18:00:14.497004	\N	zxcvbnmasdfghjkl	1	f
\.

COPY public."vaccinazioni" ("id", "id_tipo", "data_vaccinazione", "lotto", "id_animale", "is_deleted") FROM stdin;
1	1	2024-01-10 10:00:00	LOT-2024-0011	1	f
2	2	2024-01-10 10:00:00	LOT-2024-0012	1	f
3	1	2023-03-15 10:00:00	LOT-2023-0045	2	f
4	2	2023-03-15 10:00:00	LOT-2023-0046	2	f
5	3	2024-01-18 10:00:00	LOT-2024-0031	3	f
6	4	2024-01-18 10:00:00	LOT-2024-0032	3	f
7	3	2023-04-22 10:00:00	LOT-2023-0078	5	f
8	1	2024-01-15 10:00:00	LOT-2024-0019	6	f
9	2	2024-01-15 10:00:00	LOT-2024-0020	6	f
10	5	2024-01-15 10:00:00	LOT-2024-0021	6	f
11	3	2024-02-19 10:00:00	LOT-2024-0041	7	f
12	1	2023-05-20 10:00:00	LOT-2023-0099	8	f
13	1	2023-06-07 10:00:00	LOT-2023-0102	9	f
14	2	2023-06-07 10:00:00	LOT-2023-0103	9	f
15	3	2023-03-14 10:00:00	LOT-2023-0061	10	f
16	1	2023-08-10 10:00:00	LOT-2023-0121	11	f
17	3	2024-02-26 10:00:00	LOT-2024-0051	13	f
18	1	2024-01-29 10:00:00	LOT-2024-0022	14	f
19	2	2024-01-29 10:00:00	LOT-2024-0023	14	f
20	3	2024-03-19 10:00:00	LOT-2024-0062	15	f
21	1	2023-11-10 10:00:00	LOT-2023-0155	16	f
22	2	2023-11-10 10:00:00	LOT-2023-0156	16	f
23	3	2024-03-08 10:00:00	LOT-2024-0058	17	f
24	1	2023-04-25 10:00:00	LOT-2023-0088	18	f
25	1	2023-07-12 10:00:00	LOT-2023-0112	19	f
\.

COPY public."visita" ("id", "data_visita", "id_tipo_visita", "id_animale", "id_veterinario", "id_pagamento", "note", "is_deleted", "nota_privata", "stato") FROM stdin;
1	2024-01-10 09:00:00	27	1	16	\N	\N	f	\N	COMPLETATA
2	2024-01-12 10:00:00	34	2	17	\N	\N	f	\N	COMPLETATA
3	2024-01-15 11:00:00	8	6	18	\N	\N	f	\N	COMPLETATA
4	2024-01-18 12:00:00	31	3	16	\N	\N	f	\N	COMPLETATA
5	2024-01-22 13:00:00	28	10	17	\N	\N	f	\N	COMPLETATA
6	2024-01-25 14:00:00	39	8	18	\N	\N	f	\N	COMPLETATA
7	2024-01-29 15:00:00	13	14	16	\N	\N	f	\N	COMPLETATA
8	2024-02-02 16:00:00	24	5	17	\N	\N	f	\N	COMPLETATA
9	2024-02-07 09:30:00	27	9	18	\N	\N	f	\N	COMPLETATA
10	2024-02-12 10:30:00	13	16	16	\N	\N	f	\N	COMPLETATA
11	2024-02-15 11:30:00	41	4	17	\N	\N	f	\N	COMPLETATA
12	2024-02-19 12:30:00	7	7	18	\N	\N	f	\N	COMPLETATA
13	2024-02-22 13:30:00	37	11	16	\N	\N	f	\N	COMPLETATA
14	2024-02-26 14:30:00	4	13	17	\N	\N	f	\N	COMPLETATA
15	2024-03-01 15:30:00	12	1	18	\N	\N	f	\N	COMPLETATA
16	2024-03-05 16:30:00	37	19	16	\N	\N	f	\N	COMPLETATA
17	2024-03-08 09:00:00	4	17	17	\N	\N	f	\N	COMPLETATA
18	2024-03-12 10:00:00	20	18	18	\N	\N	f	\N	COMPLETATA
19	2024-03-15 11:00:00	24	6	16	\N	\N	f	\N	COMPLETATA
20	2024-03-19 12:00:00	8	15	17	\N	\N	f	\N	COMPLETATA
21	2024-03-22 13:00:00	37	2	18	\N	\N	f	\N	COMPLETATA
22	2024-03-26 14:00:00	5	20	16	\N	\N	f	\N	COMPLETATA
23	2024-04-02 15:00:00	27	12	17	\N	\N	f	\N	COMPLETATA
24	2024-04-09 16:00:00	34	3	18	\N	\N	f	\N	COMPLETATA
25	2024-04-16 09:30:00	41	14	16	\N	\N	f	\N	COMPLETATA
\.

ALTER TABLE ONLY public."animali" ADD CONSTRAINT animali_microchip_key UNIQUE (microchip);
ALTER TABLE ONLY public."animali" ADD CONSTRAINT animali_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public."animali" ADD CONSTRAINT fk_animali_utenti FOREIGN KEY (id_utente) REFERENCES utenti(id);
ALTER TABLE ONLY public."aziende" ADD CONSTRAINT aziende_partita_iva_key UNIQUE (partita_iva);
ALTER TABLE ONLY public."aziende" ADD CONSTRAINT aziende_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public."categorie_visite" ADD CONSTRAINT categorie_visite_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public."eventi_app" ADD CONSTRAINT eventi_app_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public."eventi_app" ADD CONSTRAINT fk_eventi_app_ruoli FOREIGN KEY (id_ruolo) REFERENCES ruoli(id);
ALTER TABLE ONLY public."eventi_app" ADD CONSTRAINT fk_eventi_app_utenti FOREIGN KEY (id_utente) REFERENCES utenti(id);
ALTER TABLE ONLY public."file_reference" ADD CONSTRAINT file_reference_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public."file_reference" ADD CONSTRAINT fk_file_reference_utenti FOREIGN KEY (owner) REFERENCES utenti(id);
ALTER TABLE ONLY public."orario_settimanale" ADD CONSTRAINT orario_settimanale_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public."orario_settimanale" ADD CONSTRAINT fk_orario_settimanale_utenti FOREIGN KEY (id_utente) REFERENCES utenti(id);
ALTER TABLE ONLY public."orario_settimanale" ADD CONSTRAINT ck_orario_settimanale_giorno CHECK (((giorno_settimana >= 1) AND (giorno_settimana <= 7)));
ALTER TABLE ONLY public."pagamenti" ADD CONSTRAINT pagamenti_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public."pagamenti" ADD CONSTRAINT fk_pagamenti_file_reference FOREIGN KEY (riferimento_file) REFERENCES file_reference(id);
ALTER TABLE ONLY public."pagamenti" ADD CONSTRAINT fk_pagamenti_utenti FOREIGN KEY (id_utente) REFERENCES utenti(id);
ALTER TABLE ONLY public."razze" ADD CONSTRAINT razze_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public."razze" ADD CONSTRAINT fk_razze_specie FOREIGN KEY (id_specie) REFERENCES specie(id);
ALTER TABLE ONLY public."ruoli" ADD CONSTRAINT ruoli_ruolo_key UNIQUE (ruolo);
ALTER TABLE ONLY public."ruoli" ADD CONSTRAINT ruoli_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public."specie" ADD CONSTRAINT specie_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public."tipi_vaccino" ADD CONSTRAINT tipi_vaccino_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public."tipi_visite" ADD CONSTRAINT tipi_visite_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public."tipi_visite" ADD CONSTRAINT fk_tipi_visite_categorie_visite FOREIGN KEY (id_categoria) REFERENCES categorie_visite(id);
ALTER TABLE ONLY public."tipi_visite" ADD CONSTRAINT fk_tipi_visite_utenti FOREIGN KEY (id_dottore) REFERENCES utenti(id);
ALTER TABLE ONLY public."utenti" ADD CONSTRAINT utenti_codice_fiscale_key UNIQUE (codice_fiscale);
ALTER TABLE ONLY public."utenti" ADD CONSTRAINT utenti_email_key UNIQUE (email);
ALTER TABLE ONLY public."utenti" ADD CONSTRAINT utenti_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public."utenti" ADD CONSTRAINT fk_utenti_aziende FOREIGN KEY (id_azienda) REFERENCES aziende(id);
ALTER TABLE ONLY public."utenti" ADD CONSTRAINT fk_utenti_ruoli FOREIGN KEY (id_ruolo) REFERENCES ruoli(id);
ALTER TABLE ONLY public."vaccinazioni" ADD CONSTRAINT vaccinazioni_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public."vaccinazioni" ADD CONSTRAINT fk_vaccinazioni_animali FOREIGN KEY (id_animale) REFERENCES animali(id);
ALTER TABLE ONLY public."vaccinazioni" ADD CONSTRAINT fk_vaccinazioni_tipi_vaccino FOREIGN KEY (id_tipo) REFERENCES tipi_vaccino(id);
ALTER TABLE ONLY public."visita" ADD CONSTRAINT visita_id_pagamento_key UNIQUE (id_pagamento);
ALTER TABLE ONLY public."visita" ADD CONSTRAINT visita_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public."visita" ADD CONSTRAINT fk_visita_animali FOREIGN KEY (id_animale) REFERENCES animali(id);
ALTER TABLE ONLY public."visita" ADD CONSTRAINT fk_visita_pagamenti FOREIGN KEY (id_pagamento) REFERENCES pagamenti(id);
ALTER TABLE ONLY public."visita" ADD CONSTRAINT fk_visita_tipi_visite FOREIGN KEY (id_tipo_visita) REFERENCES tipi_visite(id);
ALTER TABLE ONLY public."visita" ADD CONSTRAINT fk_visita_veterinari FOREIGN KEY (id_veterinario) REFERENCES utenti(id);

CREATE INDEX idx_animali_id_utente ON public.animali USING btree (id_utente);
CREATE INDEX idx_eventi_app_id_ruolo ON public.eventi_app USING btree (id_ruolo);
CREATE INDEX idx_eventi_app_id_utente ON public.eventi_app USING btree (id_utente);
CREATE INDEX idx_file_reference_owner ON public.file_reference USING btree (owner);
CREATE INDEX idx_orario_settimanale_id_utente ON public.orario_settimanale USING btree (id_utente);
CREATE INDEX idx_pagamenti_id_utente ON public.pagamenti USING btree (id_utente);
CREATE INDEX idx_pagamenti_riferimento_file ON public.pagamenti USING btree (riferimento_file);
CREATE INDEX idx_razze_id_specie ON public.razze USING btree (id_specie);
CREATE INDEX idx_tipi_visite_id_categoria ON public.tipi_visite USING btree (id_categoria);
CREATE INDEX idx_tipi_visite_id_dottore ON public.tipi_visite USING btree (id_dottore);
CREATE INDEX idx_utenti_id_azienda ON public.utenti USING btree (id_azienda);
CREATE INDEX idx_utenti_id_ruolo ON public.utenti USING btree (id_ruolo);
CREATE INDEX idx_vaccinazioni_id_animale ON public.vaccinazioni USING btree (id_animale);
CREATE INDEX idx_vaccinazioni_id_tipo ON public.vaccinazioni USING btree (id_tipo);
CREATE INDEX idx_visita_id_animale ON public.visita USING btree (id_animale);
CREATE INDEX idx_visita_id_tipo_visita ON public.visita USING btree (id_tipo_visita);
CREATE INDEX idx_visita_id_veterinario ON public.visita USING btree (id_veterinario);

SELECT setval(pg_get_serial_sequence('public.animali', 'id'), COALESCE((SELECT MAX("id") FROM public."animali"), 1), TRUE);
SELECT setval(pg_get_serial_sequence('public.aziende', 'id'), COALESCE((SELECT MAX("id") FROM public."aziende"), 1), TRUE);
SELECT setval(pg_get_serial_sequence('public.categorie_visite', 'id'), COALESCE((SELECT MAX("id") FROM public."categorie_visite"), 1), TRUE);
SELECT setval(pg_get_serial_sequence('public.eventi_app', 'id'), COALESCE((SELECT MAX("id") FROM public."eventi_app"), 1), TRUE);
SELECT setval(pg_get_serial_sequence('public.file_reference', 'id'), COALESCE((SELECT MAX("id") FROM public."file_reference"), 1), TRUE);
SELECT setval(pg_get_serial_sequence('public.orario_settimanale', 'id'), COALESCE((SELECT MAX("id") FROM public."orario_settimanale"), 1), TRUE);
SELECT setval(pg_get_serial_sequence('public.pagamenti', 'id'), COALESCE((SELECT MAX("id") FROM public."pagamenti"), 1), TRUE);
SELECT setval(pg_get_serial_sequence('public.razze', 'id'), COALESCE((SELECT MAX("id") FROM public."razze"), 1), TRUE);
SELECT setval(pg_get_serial_sequence('public.ruoli', 'id'), COALESCE((SELECT MAX("id") FROM public."ruoli"), 1), TRUE);
SELECT setval(pg_get_serial_sequence('public.specie', 'id'), COALESCE((SELECT MAX("id") FROM public."specie"), 1), TRUE);
SELECT setval(pg_get_serial_sequence('public.tipi_vaccino', 'id'), COALESCE((SELECT MAX("id") FROM public."tipi_vaccino"), 1), TRUE);
SELECT setval(pg_get_serial_sequence('public.tipi_visite', 'id'), COALESCE((SELECT MAX("id") FROM public."tipi_visite"), 1), TRUE);
SELECT setval(pg_get_serial_sequence('public.utenti', 'id'), COALESCE((SELECT MAX("id") FROM public."utenti"), 1), TRUE);
SELECT setval(pg_get_serial_sequence('public.vaccinazioni', 'id'), COALESCE((SELECT MAX("id") FROM public."vaccinazioni"), 1), TRUE);
SELECT setval(pg_get_serial_sequence('public.visita', 'id'), COALESCE((SELECT MAX("id") FROM public."visita"), 1), TRUE);

COMMIT;
