CREATE TABLE aziende (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ragione_sociale VARCHAR(100) NOT NULL,
    partita_iva VARCHAR(11) NOT NULL,
    forma_giuridica VARCHAR(100) NOT NULL,
    is_deleted BOOLEAN NOT NULL,
    CONSTRAINT uk_aziende_partita_iva UNIQUE (partita_iva)
);

CREATE TABLE ruoli (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ruolo VARCHAR(15) NOT NULL,
    CONSTRAINT uk_ruoli_ruolo UNIQUE (ruolo)
);

CREATE TABLE specie (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    is_deleted BOOLEAN NOT NULL
);

CREATE TABLE categorie_visite (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    is_deleted BOOLEAN NOT NULL
);

CREATE TABLE tipi_vaccino (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipologia VARCHAR(255) NOT NULL,
    durata INTEGER NOT NULL,
    note VARCHAR(255),
    is_deleted BOOLEAN NOT NULL
);

CREATE TABLE utenti (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(30) NOT NULL,
    cognome VARCHAR(30) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    codice_fiscale VARCHAR(16) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    indirizzo VARCHAR(30),
    citta VARCHAR(20),
    data_registrazione TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    id_azienda INTEGER,
    id_ruolo INTEGER NOT NULL,
    is_deleted BOOLEAN NOT NULL,
    CONSTRAINT uk_utenti_email UNIQUE (email),
    CONSTRAINT uk_utenti_codice_fiscale UNIQUE (codice_fiscale),
    CONSTRAINT fk_utenti_azienda FOREIGN KEY (id_azienda) REFERENCES aziende (id),
    CONSTRAINT fk_utenti_ruolo FOREIGN KEY (id_ruolo) REFERENCES ruoli (id)
);

CREATE TABLE animali (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(30) NOT NULL,
    specie VARCHAR(15),
    razza VARCHAR(20),
    sesso VARCHAR(10),
    data_nascita DATE NOT NULL,
    peso DOUBLE PRECISION,
    microchip VARCHAR(15),
    note TEXT,
    is_deleted BOOLEAN NOT NULL,
    id_utente INTEGER NOT NULL,
    CONSTRAINT uk_animali_microchip UNIQUE (microchip),
    CONSTRAINT fk_animali_utente FOREIGN KEY (id_utente) REFERENCES utenti (id)
);

CREATE TABLE razze (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    id_specie INTEGER NOT NULL,
    is_deleted BOOLEAN NOT NULL,
    CONSTRAINT fk_razze_specie FOREIGN KEY (id_specie) REFERENCES specie (id)
);

CREATE TABLE file_reference (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_file_name VARCHAR(255) NOT NULL,
    stored_file_name VARCHAR(255) NOT NULL,
    mime_type VARCHAR(255) NOT NULL,
    ssize BIGINT NOT NULL,
    storage_path VARCHAR(255) NOT NULL,
    owner INTEGER NOT NULL,
    upload_date TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    is_deleted BOOLEAN NOT NULL,
    CONSTRAINT fk_file_reference_owner FOREIGN KEY (owner) REFERENCES utenti (id)
);

CREATE TABLE pagamenti (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL,
    tipo_pagamento VARCHAR(30),
    importo_totale NUMERIC(8, 2) NOT NULL,
    id_utente INTEGER,
    riferimento_file INTEGER,
    is_deleted BOOLEAN NOT NULL,
    CONSTRAINT fk_pagamenti_utente FOREIGN KEY (id_utente) REFERENCES utenti (id),
    CONSTRAINT fk_pagamenti_file FOREIGN KEY (riferimento_file) REFERENCES file_reference (id)
);

CREATE TABLE tipi_visite (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(80) NOT NULL,
    durata INTEGER NOT NULL,
    id_categoria INTEGER,
    prezzo NUMERIC(8, 2) NOT NULL,
    id_dottore INTEGER NOT NULL,
    is_deleted BOOLEAN NOT NULL,
    attivo BOOLEAN NOT NULL,
    CONSTRAINT fk_tipi_visite_categoria FOREIGN KEY (id_categoria) REFERENCES categorie_visite (id),
    CONSTRAINT fk_tipi_visite_dottore FOREIGN KEY (id_dottore) REFERENCES utenti (id)
);

CREATE TABLE vaccinazioni (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo INTEGER NOT NULL,
    data_vaccinazione TIMESTAMP(6) WITHOUT TIME ZONE,
    lotto VARCHAR(255),
    id_animale INTEGER NOT NULL,
    is_deleted BOOLEAN NOT NULL,
    CONSTRAINT fk_vaccinazioni_tipo FOREIGN KEY (id_tipo) REFERENCES tipi_vaccino (id),
    CONSTRAINT fk_vaccinazioni_animale FOREIGN KEY (id_animale) REFERENCES animali (id)
);

CREATE TABLE visita (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_visita TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    id_tipo_visita INTEGER NOT NULL,
    id_animale INTEGER NOT NULL,
    id_veterinario INTEGER NOT NULL,
    id_pagamento INTEGER,
    note VARCHAR(255),
    nota_privata VARCHAR(255),
    stato VARCHAR(255) NOT NULL,
    is_deleted BOOLEAN NOT NULL,
    CONSTRAINT uk_visita_pagamento UNIQUE (id_pagamento),
    CONSTRAINT ck_visita_stato CHECK (stato IN ('PRENOTATA', 'COMPLETATA')),
    CONSTRAINT fk_visita_tipo FOREIGN KEY (id_tipo_visita) REFERENCES tipi_visite (id),
    CONSTRAINT fk_visita_animale FOREIGN KEY (id_animale) REFERENCES animali (id),
    CONSTRAINT fk_visita_veterinario FOREIGN KEY (id_veterinario) REFERENCES utenti (id),
    CONSTRAINT fk_visita_pagamento FOREIGN KEY (id_pagamento) REFERENCES pagamenti (id)
);

CREATE TABLE orario_settimanale (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    giorno_settimana INTEGER NOT NULL,
    mattina_inizio INTEGER NOT NULL,
    mattina_fine INTEGER NOT NULL,
    pomeriggio_inizio INTEGER NOT NULL,
    pomeriggio_fine INTEGER NOT NULL,
    id_utente INTEGER NOT NULL,
    CONSTRAINT fk_orario_settimanale_utente FOREIGN KEY (id_utente) REFERENCES utenti (id)
);

CREATE TABLE eventi_app (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_utente INTEGER NOT NULL,
    id_ruolo INTEGER NOT NULL,
    tipo_evento VARCHAR(20) NOT NULL,
    id_oggetto INTEGER,
    oggetto_azione VARCHAR(30),
    time_stamp TIMESTAMP(6) WITHOUT TIME ZONE,
    metadata JSONB,
    CONSTRAINT fk_eventi_app_utente FOREIGN KEY (id_utente) REFERENCES utenti (id),
    CONSTRAINT fk_eventi_app_ruolo FOREIGN KEY (id_ruolo) REFERENCES ruoli (id)
);

CREATE TABLE richieste_valutazione_animali (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(30) NOT NULL,
    specie VARCHAR(30) NOT NULL,
    razza VARCHAR(40) NOT NULL,
    sesso VARCHAR(10) NOT NULL,
    data_nascita DATE NOT NULL,
    peso DOUBLE PRECISION NOT NULL,
    microchip VARCHAR(15),
    note TEXT,
    descrizione TEXT NOT NULL,
    data_richiesta TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    is_deleted BOOLEAN NOT NULL,
    id_utente INTEGER NOT NULL,
    CONSTRAINT fk_richieste_valutazione_utente FOREIGN KEY (id_utente) REFERENCES utenti (id)
);

CREATE INDEX idx_utenti_id_azienda ON utenti (id_azienda);
CREATE INDEX idx_utenti_id_ruolo ON utenti (id_ruolo);
CREATE INDEX idx_animali_id_utente ON animali (id_utente);
CREATE INDEX idx_razze_id_specie ON razze (id_specie);
CREATE INDEX idx_file_reference_owner ON file_reference (owner);
CREATE INDEX idx_file_reference_upload_date ON file_reference (upload_date);
CREATE INDEX idx_pagamenti_id_utente ON pagamenti (id_utente);
CREATE INDEX idx_pagamenti_riferimento_file ON pagamenti (riferimento_file);
CREATE INDEX idx_tipi_visite_id_categoria ON tipi_visite (id_categoria);
CREATE INDEX idx_tipi_visite_id_dottore ON tipi_visite (id_dottore);
CREATE INDEX idx_vaccinazioni_id_tipo ON vaccinazioni (id_tipo);
CREATE INDEX idx_vaccinazioni_id_animale_data ON vaccinazioni (id_animale, data_vaccinazione DESC);
CREATE INDEX idx_visita_id_tipo_visita ON visita (id_tipo_visita);
CREATE INDEX idx_visita_id_animale_data ON visita (id_animale, data_visita);
CREATE INDEX idx_visita_id_veterinario_data ON visita (id_veterinario, data_visita);
CREATE INDEX idx_orario_settimanale_utente_giorno ON orario_settimanale (id_utente, giorno_settimana);
CREATE INDEX idx_eventi_app_id_utente ON eventi_app (id_utente);
CREATE INDEX idx_eventi_app_id_ruolo ON eventi_app (id_ruolo);
CREATE INDEX idx_richieste_valutazione_data ON richieste_valutazione_animali (data_richiesta DESC);
CREATE INDEX idx_richieste_valutazione_utente ON richieste_valutazione_animali (id_utente);
