CREATE TABLE aziende (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ragione_sociale VARCHAR(100) NOT NULL,
    partita_iva VARCHAR(100) NOT NULL UNIQUE,
    forma_giuridica VARCHAR(100) NOT NULL
);

CREATE TABLE ruoli (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ruolo VARCHAR(15) NOT NULL UNIQUE
);

CREATE TABLE utenti (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(30) NOT NULL,
    cognome VARCHAR(30) NOT NULL,
    email VARCHAR(100) UNIQUE,
    password VARCHAR(255) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    indirizzo VARCHAR(30),
    citta VARCHAR(20),
    data_registrazione DATE NOT NULL,
    id_azienda INTEGER,
    riferimento VARCHAR(30),
    id_ruolo INTEGER,
    CONSTRAINT fk_utenti_aziende
        FOREIGN KEY (id_azienda) REFERENCES aziende(id),
    CONSTRAINT fk_utenti_ruoli
        FOREIGN KEY (id_ruolo) REFERENCES ruoli(id)
);

CREATE TABLE animali (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(30) NOT NULL,
    specie VARCHAR(15),
    razza VARCHAR(20),
    sesso VARCHAR(10),
    data_nascita DATE NOT NULL,
    peso DOUBLE PRECISION,
    microchip VARCHAR(15) UNIQUE,
    note TEXT,
    id_utente INTEGER NOT NULL,
    CONSTRAINT fk_animali_utenti
        FOREIGN KEY (id_utente) REFERENCES utenti(id)
);

CREATE TABLE tipi_vaccino (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipologia VARCHAR(40) NOT NULL,
    durata INTEGER NOT NULL,
    note TEXT
);

CREATE TABLE vaccinazioni (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo INTEGER NOT NULL,
    data_vaccinazione DATE,
    lotto VARCHAR(10),
    id_animale INTEGER NOT NULL,
    CONSTRAINT fk_vaccinazioni_tipi_vaccino
        FOREIGN KEY (id_tipo) REFERENCES tipi_vaccino(id),
    CONSTRAINT fk_vaccinazioni_animali
        FOREIGN KEY (id_animale) REFERENCES animali(id)
);

CREATE TABLE categorie_visite (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL
);

CREATE TABLE tipi_visite (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(80) NOT NULL,
    durata INTEGER NOT NULL,
    id_categoria INTEGER,
    prezzo DECIMAL(8, 2) NOT NULL,
    attivo BOOLEAN NOT NULL DEFAULT TRUE,
    id_dottore INTEGER NOT NULL,
    CONSTRAINT fk_tipi_visite_categorie_visite
        FOREIGN KEY (id_categoria) REFERENCES categorie_visite(id),
    CONSTRAINT fk_tipi_visite_utenti
        FOREIGN KEY (id_dottore) REFERENCES utenti(id)
);

CREATE TABLE pagamenti (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL,
    tipo_pagamento VARCHAR(30),
    importo_totale DECIMAL(8, 2) NOT NULL,
    id_utente INTEGER,
    CONSTRAINT fk_pagamenti_utenti
        FOREIGN KEY (id_utente) REFERENCES utenti(id)
);

CREATE TABLE visite (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_animale INTEGER NOT NULL,
    data_visita TIMESTAMP NOT NULL,
    id_tipo INTEGER NOT NULL,
    id_dottore INTEGER NOT NULL,
    id_pagamento INTEGER,
    note TEXT,
    CONSTRAINT fk_visite_animali
        FOREIGN KEY (id_animale) REFERENCES animali(id),
    CONSTRAINT fk_visite_tipi_visite
        FOREIGN KEY (id_tipo) REFERENCES tipi_visite(id),
    CONSTRAINT fk_visite_utenti
        FOREIGN KEY (id_dottore) REFERENCES utenti(id),
    CONSTRAINT fk_visite_pagamenti
        FOREIGN KEY (id_pagamento) REFERENCES pagamenti(id)
);

CREATE TABLE prenotazioni (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_visita TIMESTAMP NOT NULL,
    id_animale INTEGER NOT NULL,
    id_tipi_visita INTEGER NOT NULL,
    CONSTRAINT fk_prenotazioni_animali
        FOREIGN KEY (id_animale) REFERENCES animali(id),
    CONSTRAINT fk_prenotazioni_tipi_visite
        FOREIGN KEY (id_tipi_visita) REFERENCES tipi_visite(id)
);

CREATE TABLE eventi_app (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_utente INTEGER NOT NULL,
    id_ruolo INTEGER NOT NULL,
    tipo_evento VARCHAR(20) NOT NULL,
    id_oggetto INTEGER,
    oggetto_azione VARCHAR(30),
    time_stamp TIMESTAMP,
    metadata JSONB,
    CONSTRAINT fk_eventi_app_utenti
        FOREIGN KEY (id_utente) REFERENCES utenti(id),
    CONSTRAINT fk_eventi_app_ruoli
        FOREIGN KEY (id_ruolo) REFERENCES ruoli(id)
);

CREATE TABLE orario_settimanale (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_utente INTEGER NOT NULL,
    giorno_settimana INTEGER NOT NULL,
    mattina_inizio TIME NOT NULL,
    mattina_fine TIME NOT NULL,
    pomeriggio_inizio TIME NOT NULL,
    pomeriggio_fine TIME NOT NULL,
    CONSTRAINT fk_orario_settimanale_utenti
        FOREIGN KEY (id_utente) REFERENCES utenti(id),
    CONSTRAINT ck_orario_settimanale_giorno
        CHECK (giorno_settimana BETWEEN 1 AND 7)
);
