-- PostgreSQL schema generated from the Spring Boot JPA entities.
-- Source package: ProgettoSpring/LBP-App-Vet/src/main/java/com/WW/entities
--
-- Notes:
-- - Identifiers are written in lowercase snake_case to match PostgreSQL's
--   unquoted identifier behavior and Spring Boot/Hibernate naming conventions.
-- - This file follows the current entity mappings, not every older note in
--   Tabelle_EasyRead.md. For example, VISITA is currently singular in the
--   entity and OrarioSettimanale stores hour values as integers.

BEGIN;

CREATE TABLE IF NOT EXISTS aziende (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ragione_sociale VARCHAR(100) NOT NULL,
    partita_iva VARCHAR(11) NOT NULL UNIQUE,
    forma_giuridica VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS ruoli (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ruolo VARCHAR(15) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS specie (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS utenti (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(30) NOT NULL,
    cognome VARCHAR(30) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    indirizzo VARCHAR(30),
    citta VARCHAR(20),
    data_registrazione TIMESTAMP NOT NULL,
    id_azienda INTEGER,
    codice_fiscale VARCHAR(16) NOT NULL UNIQUE,
    id_ruolo INTEGER NOT NULL,
    CONSTRAINT fk_utenti_aziende
        FOREIGN KEY (id_azienda) REFERENCES aziende(id),
    CONSTRAINT fk_utenti_ruoli
        FOREIGN KEY (id_ruolo) REFERENCES ruoli(id)
);

CREATE TABLE IF NOT EXISTS razze (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    id_specie INTEGER NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_razze_specie
        FOREIGN KEY (id_specie) REFERENCES specie(id)
);

CREATE TABLE IF NOT EXISTS animali (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(30) NOT NULL,
    specie VARCHAR(15),
    razza VARCHAR(20),
    sesso VARCHAR(10),
    data_nascita DATE NOT NULL,
    peso DOUBLE PRECISION,
    microchip VARCHAR(15) UNIQUE,
    note TEXT,
    id_utente INTEGER NOT NULL,
    CONSTRAINT fk_animali_utenti
        FOREIGN KEY (id_utente) REFERENCES utenti(id)
);

CREATE TABLE IF NOT EXISTS categorie_visite (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS tipi_vaccino (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipologia VARCHAR(255) NOT NULL,
    durata INTEGER NOT NULL,
    note VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS tipi_visite (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(80) NOT NULL,
    durata INTEGER NOT NULL,
    id_categoria INTEGER,
    prezzo NUMERIC(8, 2) NOT NULL,
    id_dottore INTEGER NOT NULL,
    attivo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_tipi_visite_categorie_visite
        FOREIGN KEY (id_categoria) REFERENCES categorie_visite(id),
    CONSTRAINT fk_tipi_visite_utenti
        FOREIGN KEY (id_dottore) REFERENCES utenti(id)
);

CREATE TABLE IF NOT EXISTS pagamenti (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL,
    tipo_pagamento VARCHAR(30),
    importo_totale NUMERIC(8, 2) NOT NULL,
    id_utente INTEGER,
    CONSTRAINT fk_pagamenti_utenti
        FOREIGN KEY (id_utente) REFERENCES utenti(id)
);

CREATE TABLE IF NOT EXISTS visita (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_visita TIMESTAMP NOT NULL,
    id_tipo_visita INTEGER NOT NULL,
    id_animale INTEGER NOT NULL,
    id_veterinario INTEGER NOT NULL,
    id_pagamento INTEGER UNIQUE,
    note VARCHAR(255),
    CONSTRAINT fk_visita_tipi_visite
        FOREIGN KEY (id_tipo_visita) REFERENCES tipi_visite(id),
    CONSTRAINT fk_visita_animali
        FOREIGN KEY (id_animale) REFERENCES animali(id),
    CONSTRAINT fk_visita_veterinari
        FOREIGN KEY (id_veterinario) REFERENCES utenti(id),
    CONSTRAINT fk_visita_pagamenti
        FOREIGN KEY (id_pagamento) REFERENCES pagamenti(id)
);

CREATE TABLE IF NOT EXISTS vaccinazioni (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo INTEGER NOT NULL,
    data_vaccinazione TIMESTAMP,
    lotto VARCHAR(255),
    id_animale INTEGER NOT NULL,
    CONSTRAINT fk_vaccinazioni_tipi_vaccino
        FOREIGN KEY (id_tipo) REFERENCES tipi_vaccino(id),
    CONSTRAINT fk_vaccinazioni_animali
        FOREIGN KEY (id_animale) REFERENCES animali(id)
);

CREATE TABLE IF NOT EXISTS eventi_app (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_utente INTEGER NOT NULL,
    id_ruolo INTEGER NOT NULL,
    tipo_evento VARCHAR(20) NOT NULL,
    id_oggetto INTEGER,
    oggetto_azione VARCHAR(30),
    time_stamp TIMESTAMP,
    metadata JSONB,
    CONSTRAINT fk_eventi_app_utenti
        FOREIGN KEY (id_utente) REFERENCES utenti(id),
    CONSTRAINT fk_eventi_app_ruoli
        FOREIGN KEY (id_ruolo) REFERENCES ruoli(id)
);

CREATE TABLE IF NOT EXISTS orario_settimanale (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    giorno_settimana INTEGER NOT NULL,
    mattina_inizio INTEGER NOT NULL,
    mattina_fine INTEGER NOT NULL,
    pomeriggio_inizio INTEGER NOT NULL,
    pomeriggio_fine INTEGER NOT NULL,
    id_utente INTEGER NOT NULL,
    CONSTRAINT fk_orario_settimanale_utenti
        FOREIGN KEY (id_utente) REFERENCES utenti(id),
    CONSTRAINT ck_orario_settimanale_giorno
        CHECK (giorno_settimana BETWEEN 1 AND 7)
);

CREATE TABLE IF NOT EXISTS file_reference (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_file_name VARCHAR(255) NOT NULL,
    stored_file_name VARCHAR(255) NOT NULL,
    mime_type VARCHAR(255) NOT NULL,
    ssize BIGINT NOT NULL,
    storage_path VARCHAR(255) NOT NULL,
    owner INTEGER NOT NULL,
    upload_date TIMESTAMP NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_file_reference_utenti
        FOREIGN KEY (owner) REFERENCES utenti(id)
);

CREATE INDEX IF NOT EXISTS idx_utenti_id_azienda ON utenti(id_azienda);
CREATE INDEX IF NOT EXISTS idx_utenti_id_ruolo ON utenti(id_ruolo);
CREATE INDEX IF NOT EXISTS idx_razze_id_specie ON razze(id_specie);
CREATE INDEX IF NOT EXISTS idx_animali_id_utente ON animali(id_utente);
CREATE INDEX IF NOT EXISTS idx_tipi_visite_id_categoria ON tipi_visite(id_categoria);
CREATE INDEX IF NOT EXISTS idx_tipi_visite_id_dottore ON tipi_visite(id_dottore);
CREATE INDEX IF NOT EXISTS idx_pagamenti_id_utente ON pagamenti(id_utente);
CREATE INDEX IF NOT EXISTS idx_visita_id_tipo_visita ON visita(id_tipo_visita);
CREATE INDEX IF NOT EXISTS idx_visita_id_animale ON visita(id_animale);
CREATE INDEX IF NOT EXISTS idx_visita_id_veterinario ON visita(id_veterinario);
CREATE INDEX IF NOT EXISTS idx_vaccinazioni_id_tipo ON vaccinazioni(id_tipo);
CREATE INDEX IF NOT EXISTS idx_vaccinazioni_id_animale ON vaccinazioni(id_animale);
CREATE INDEX IF NOT EXISTS idx_eventi_app_id_utente ON eventi_app(id_utente);
CREATE INDEX IF NOT EXISTS idx_eventi_app_id_ruolo ON eventi_app(id_ruolo);
CREATE INDEX IF NOT EXISTS idx_orario_settimanale_id_utente ON orario_settimanale(id_utente);
CREATE INDEX IF NOT EXISTS idx_file_reference_owner ON file_reference(owner);

COMMIT;
