spring.application.name=LBP-App-Vet

server.port=9020

spring.datasource.url=jdbc:postgresql://pg-3c1a4084-learningbyproject-edu-0b7e.i.aivencloud.com:11216/defaultdb?ssl=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_hGTjwI1mcIfGTy97iIi